version: 2.1

orbs:
  php: circleci/php@1.1.0
  
jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  phpdocjob:
  # This is our first job.
    docker:
    # it uses the docker executor
      - image: phpdoc/phpdoc
        # authentication if required ?
        # auth:
        #  username: mydockerhub-user
        #  password: $DOCKERHUB_PASSWORD
        # context / project UI env-var reference
    working_directory: /app
    # Steps are a list of commands to run inside the docker container above.
    steps:
      # this pulls code down from GitHub
      - checkout:
          path: src
      # This prints "A first hello" to stdout.
      - run: echo "Hello into Phpdoc container !" $(pwd)
      # generate phpdoc from /app into /phpdocs ignore vendor and tests folders
      - run: phpdoc -d src -t phpdocs --ignore "vendor/,tests/,install/update" --template="responsive-twig" --defaultpackagename Jeedom --title "Jeedom Core"
      - run: ls -als
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: /app
          # Must be relative path from root
          paths: phpdocs

  # This is our second job.
  phpstanjob:
    docker:
      - image: ghcr.io/phpstan/phpstan
    working_directory: /app
    steps:
      - checkout
      # We run a similar echo command to above.
      - run: echo "Hi into PhpStan :) " $(pwd)
      - run: ls -als
      - run: phpstan analyse . --level 6

  # deploy generated doc to github gh-pages
  docs-deploy:
    docker:
      - image: node:8.10.0
    working_directory: /app
    steps:
      - checkout
      - attach_workspace:
          at: phpdocs
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "nicolas_gras@hotmail.com"
            git config user.name "pifou25"
      # add ssh key fingerprint, see:
      # https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/
      - add_ssh_keys:
          fingerprints:
            - "fa:d8:0c:b2:d7:7b:73:4c:72:f9:8a:5a:20:0c:7d:1e"
      - run: ls -als
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "[skip ci] Update PhpDoc" --src phpdocs/**/* --dist . --dotfiles

# Under the workflows: map, we can coordinate our two jobs, defined above.
workflows:
  version: 2.1
  # this is the name of our workflow
  Analyse_and_PhpDocument:
    # and here we list the jobs we are going to run.
    jobs:
      # - phpstanjob
      - phpdocjob:
          # add a filter for this job
          filters:
            # only run this job on phpdocs branch
            branches:
              only: phpdocs
      - docs-deploy:
          requires:
            - phpdocjob
          filters:
            branches:
              only: phpdocs
