# build docker image based on debian bullseye and bookworm
# start both containers and run sick.php
# stop & clean
name: Docker Test TRixie Image

on:
  # only trigger CI when pull request on following branches
  pull_request:
    branches:
      - 'alpha'
  push:
    branches:
      - trixie_test
  # this is to manually trigger the worklow
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'     
        default: 'Manual launch'

jobs:
  buildAndTestDockerImg:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo
        # Check out the repo, using current branch
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v4

      - name: Build jeedom:trixie
        # build current image for trixie
        run: |
          docker build -t jeedom:trixie --build-arg DEBIAN=trixie --build-arg DATABASE=1 .
      - name: run jeedom:trixie and check
        # run current image for trixie and check it
        run: |
          docker run -p 80:80 -d --rm --name jeedom_trixie jeedom:trixie
          sleep 45
          docker exec jeedom_trixie php sick.php
      - name: Build jeedom:bookworm
        # build current image for bookworm
        run: |
          docker build -t jeedom:bookworm --build-arg DEBIAN=bookworm --build-arg DATABASE=1 .
      - name: run jeedom:bookworm and check
        # run current image for bookworm and check it
        run: |
          docker run -p 81:80 -d --rm --name jeedom_bookworm jeedom:bookworm
          sleep 45
          docker exec jeedom_bookworm php sick.php
    
      - name: Clean docker image
        continue-on-error: true
        run: |
          docker stop jeedom_trixie  jeedom_bookworm || true
          docker rm jeedom_trixie jeedom_bookworm || true
          docker rmi jeedom:trixie jeedom:bookworm || true
