name: Docker Image CI
on:
  schedule:
    - cron: "00 00 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3.3.0

      - name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        # https://github.com/marketplace/actions/docker-setup-qemu
        # set up more platforms (default = all)
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Hub
        # https://github.com/marketplace/actions/docker-login
        # login to DockerHub with secrets login & token
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        # https://github.com/marketplace/actions/docker-setup-buildx
        # set up a multi-platform builder for Docker containers
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        # https://github.com/marketplace/actions/build-and-push-docker-images
        # this job build the docker image and push into Docker Hub
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          build-args: VERSION=${{ env.BRANCH }}
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/jeedom:${{ env.BRANCH }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
