name: PHP Doc Generator

on:
  push:
    branches: [ phpdocs ]
  pull_request:
    branches: [ phpdocs ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: PHP CS Fixer
      uses: StephaneBour/actions-php-cs-fixer@1.0
      with:
        dir: './src'

    - name: PhpDocumentor
      uses: gpupo/actions-phpDocumentor@1.0
      with:
        dir: './'

    - name: Commit files
      run: |
        git config --local user.email "nicolas_gras@hotmail.com"
        git config --local user.name "pifou25[bot]"
        git add phpdocs/\*
        git commit -m "[auto] update phpdoc from Github Actions" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
