name: PHP Composer

on:
  push:
    branches: [ phpdocs ]
  pull_request:
    branches: [ phpdocs ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#    - name: Validate composer.json and composer.lock
#      run: composer validate --strict

#    - name: Cache Composer packages
#      id: composer-cache
#      uses: actions/cache@v2
#      with:
#        path: vendor
#        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-php-

#    - name: Install dependencies
#      run: composer install --prefer-dist --no-progress

    - name: PhpDocumentor
      uses: gpupo/actions-phpDocumentor@1.0
      with:
        dir: './'

    - name: Commit files
      run: |
        git config --local user.email "nicolas_gras@hotmail.com"
        git config --local user.name "pifou25[bot]"
        git commit -m "[auto] update phpdoc from Github Actions" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        
#    - name: Deploy
#      uses: pifou25/jeedom-core@phpdocs
#      with:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        BRANCH: gh-pages
#        FOLDER: phpdocs
#        CLEAN: true

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
