on:
  # Create branch > prettier / this workflows create commit on branch prettier.
  push:
    branches:
      - prettier
      - trixie_test
  pull_request:
    branches:
      - prettier

name : 'Prettier Plugin Jeedom'

jobs:
  prettier:
    uses: pifou25/jeedom-workflows/.github/workflows/prettier.yml@main
    # uses: jeedom/workflows/.github/workflows/prettier.yml@main
